### ISSUE TITLE
.

### ISSUE THREAD

**Issue by theb1rd57** [tomaszpoliszuk/PortraitPhotos#1]

**Comment by tomaszpoliszuk** [comment]
Those are required dependencies:
- firmware (>= 12.4)
- mobilesubstrate
- gsc.rear-facing-telephoto-camera-capability

Looks like your device does not meet these criteria.

Could you tell me what device it is and on what iOS version?

**Comment by tomaszpoliszuk** [comment]
I'm closing this issue for lack of response.
